apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.15.0           # dernière LTS
    releaseName: cert-manager
    valuesInline:
      installCRDs: true
