# .github/workflows/deploy-prod.yml
name: Deploy infra to prod

on:
  push:
    branches: [main]
    paths:
      - 'cluster/**'
      - '.github/workflows/deploy-prod.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v4

      - name: Set up kubectl & kustomize
        uses: azure/setup-kubectl@v4
      - run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/kustomize

      - name: Auth to cluster
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_PROD }}
        run: |
          echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config

      - name: Deploy overlay prod
        run: |
          kustomize build cluster/overlays/prod | kubectl apply -f -
