name: Deploy infra (dev)

on:
  push:
    branches: [main]
    paths:
      - "cluster/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl & kustomize
        run: |
          curl -s https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh | bash
          sudo mv kustomize /usr/local/bin/
          sudo apt-get update -y && sudo apt-get install -y kubectl

      - name: Set kubeconfig
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DEV }}
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG" | base64 -d > $HOME/.kube/config

      - name: Deploy overlay dev
        run: |
          kustomize build cluster/overlays/dev | kubectl apply -f -
