name: Lint placeholders

on:
  push:
    branches: [ main, feat/** ]
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Skip for now
        run: echo "No lint configured yet – skipping"
